Merge ZoL PR 3337 - Base init scripts for SYSV systems + Remove old init scripts from source. + Remove patch that removes the init scripts. + Remove the now defunct 'zed' script (renamed to 'zfs-zed') from install. + Install new init scripts into package. + Update list of what to install into zfsutils.deb + Because of new init scripts (which also includes a default file),   don't install the one from the zfs-initramfs dir. + Init script is installed by upstream, so add '--onlyscripts' to dh_installinit.

diff --git a/etc/init.d/zfs-zed.in b/etc/init.d/zfs-zed.in
--- a/etc/init.d/zfs-zed.in
+++ b/etc/init.d/zfs-zed.in
@@ -1,9 +1,9 @@
-#!/bin/sh
+#!/bin/bash
 
 ### BEGIN INIT INFO
-# Provides:          zed zeventd
-# Required-Start:    $remote_fs zfs
-# Required-Stop:     $remote_fs zfs
+# Provides:          zed zeventd zfs-zed
+# Required-Start:    $local_fs zpool
+# Required-Stop:     $local_fs zpool
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: ZFS Event Daemon
@@ -14,50 +14,36 @@
 
 # Author: Turbo Fredriksson <turbo@bayour.com>
 
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
-DESC="ZFS Event Daemon"
-NAME=zed
-DAEMON=/sbin/$NAME
-DAEMON_ARGS=""
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
+# Source the common init script
+. @sysconfdir@/zfs/common.init
+servicename=zfs-zed
 
 # Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
+[ -x "$ZED" ] || exit 0
 
 # Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+[ -r /etc/default/$servicename ] && . /etc/default/$servicename
 
-# Load the VERBOSE setting and other rcS variables
-. /lib/init/vars.sh
-
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
-# and status_of_proc is working.
-. /lib/lsb/init-functions
-
-#
 # Function that starts the daemon/service
-#
 do_start()
 {
 	# Return
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
+
+	start-stop-daemon --start --quiet --pidfile /var/run/$servicename.pid --exec $ZED \
+		--test > /dev/null || return 1
+
+	start-stop-daemon --start --quiet --pidfile /var/run/$servicename.pid --exec $ZED \
+		-- $DAEMON_ARGS || return 2
+
 	# Add code here, if necessary, that waits for the process to be ready
 	# to handle requests from services started subsequently which depend
 	# on this one.  As a last resort, sleep for some time.
 }
 
-#
 # Function that stops the daemon/service
-#
 do_stop()
 {
 	# Return
@@ -65,19 +51,23 @@ do_stop()
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
+		--pidfile /var/run/$servicename.pid --name $servicename
 	RETVAL="$?"
 	[ "$RETVAL" = 2 ] && return 2
+
 	# Wait for children to finish too if this is a daemon that forks
 	# and if the daemon is only ever run from this initscript.
 	# If the above conditions are not satisfied then add some other code
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $ZED
 	[ "$?" = 2 ] && return 2
+
 	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
+	rm -f /var/run/$servicename.pid
 	return "$RETVAL"
 }
 
@@ -85,59 +75,58 @@ do_stop()
 # Function that sends a SIGHUP to the daemon/service
 #
 do_reload() {
-	#
 	# If the daemon can reload its configuration without
 	# restarting (for example, when it is sent a SIGHUP),
 	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+
+	start-stop-daemon --stop --signal 1 --quiet \
+		--pidfile /var/run/$servicename.pid --name $servicename
 	return 0
 }
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && $log_begin_msg "Starting ZFS Event Daemon" "$servicename"
 	do_start
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0|1) [ "$VERBOSE" != no ] && $log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && $log_end_msg 1 ;;
 	esac
 	;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && $log_begin_msg "Stopping ZFS Event Daemon" "$servicename"
 	do_stop
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0|1) [ "$VERBOSE" != no ] && $log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && $log_end_msg 1 ;;
 	esac
 	;;
   status)
-	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	status_of_proc "$ZED" "$servicename" && exit 0 || exit $?
 	;;
   reload|force-reload)
-	log_daemon_msg "Reloading $DESC" "$NAME"
+	$log_begin_msg "Reloading ZFS Event Daemon" "$servicename"
 	do_reload
-	log_end_msg $?
+	$log_end_msg $?
 	;;
   restart)
-	#
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
+
+	$log_begin_msg "Restarting ZFS Event Daemon" "$servicename"
 	do_stop
 	case "$?" in
 	  0|1)
 		do_start
 		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+			0) $log_end_msg 0 ;;
+			1) $log_end_msg 1 ;; # Old process is still running
+			*) $log_end_msg 1 ;; # Failed to start
 		esac
 		;;
 	  *)
 		# Failed to stop
-		log_end_msg 1
+		$log_end_msg 1
 		;;
 	esac
 	;;
@@ -147,4 +136,4 @@ case "$1" in
 	;;
 esac
 
-:
+exit 0
