Add functionality that exists in initramfs to dracut.
* Support 'zfs:<rootfs>' import and mounting.
  This was for some reason removed in eda3d4e1de94cd3a9247bb90a64413a89e736847.
* Support booting from snapshots.
* Support mounting recursive filesystems.
* Support mounting of additional filesystems.
* Support mounting nativly encrypted filesystems.

* Move code snippet that fetches and mounts recursive filesystems into recursive_mount_filesystems().
* zfs_set_ifs() needs to be a global func. We need it in a number of places!
  * Use this wherever we use CMD="somecmd someopt someopt" ; OUT="$($CMD someopt)"
* Dracut have the func emergency_shell() which does a little more.
  For those that don't have it, just run '/bin/sh -i -l'.

diff --git a/contrib/shell-common/zfs-functions.in b/contrib/shell-common/zfs-functions.in
--- a/contrib/shell-common/zfs-functions.in
+++ b/contrib/shell-common/zfs-functions.in
@@ -41,17 +41,6 @@ if type log_failure_msg > /dev/null 2>&1 ; then
 	zfs_log_progress_msg() { log_progress_msg "$1"; }
 elif type success > /dev/null 2>&1 ; then
 	# Fedora/RedHat functions
-	zfs_set_ifs() {
-		# For some reason, the init function library have a problem
-		# with a changed IFS, so this function goes around that.
-		local tIFS="$1"
-		if [ -n "$tIFS" ]
-		then
-			TMP_IFS="$IFS"
-			IFS="$tIFS"
-		fi
-	}
-
 	zfs_log_begin_msg() { echo -n "$1 "; }
 	zfs_log_end_msg() {
 		zfs_set_ifs "$OLD_IFS"
@@ -336,6 +325,35 @@ check_module_loaded()
 	[ -r "/sys/module/${module}/version" ] && return 0 || return 1
 }
 
+# Recursivly mount all filesystems, including any additional filesystems,
+# below the specified filesystem.
+recursive_mount_filesystems()
+{
+	local msg="$1"
+	local fs="$2"
+	local filesystems f
+
+	# Only fail here if the first fs fails to mount.
+	if zfs_action "$msg" mount_fs "${fs}"; then
+		# Go through the complete list (recursivly) of all filesystems
+		# below the first (root) dataset.
+		filesystems=$("${ZFS}" list -oname -tfilesystem -H -r "${fs}")
+		for f in $filesystems $ZFS_INITRD_ADDITIONAL_DATASETS
+		do
+			# Ignore the first (root) fs. Should already be
+			# mounted, but is still included in the 'zfs list'
+			#  above.
+			[ "${f}" = "${fs}" ] && continue
+
+			zfs_action "Mounting filesystem $f" mount_fs "${f}"
+		done
+	else
+		return 1
+	fi
+
+	return 0
+}
+
 load_module()
 {
 	module="$1"
@@ -492,7 +510,7 @@ find_pools()
 	local CMD="$*"
 	local pools
 
-	pools=$($CMD 2> /dev/null | \
+	pools=$(${CMD} 2> /dev/null | \
 		grep -E "pool:|^[a-zA-Z0-9]" | \
 		sed 's@.*: @@' | \
 		sort | \
@@ -618,7 +636,9 @@ import_pool()
 		"Importing pool '${pool}' using defaults"
 
 	ZFS_CMD="${ZPOOL} import -N ${ZPOOL_FORCE} ${ZPOOL_IMPORT_OPTS}"
+	zfs_set_ifs "$OLD_IFS"
 	ZFS_STDERR="$($ZFS_CMD "$pool" 2>&1)"
+	zfs_set_ifs "$TMP_IFS"
 	ZFS_ERROR="$?"
 	if [ "${ZFS_ERROR}" != 0 ]
 	then
@@ -628,21 +648,28 @@ import_pool()
 			"Importing pool '${pool}' using cachefile."
 
 		ZFS_CMD="${ZPOOL} import -c ${ZPOOL_CACHE} -N ${ZPOOL_FORCE} ${ZPOOL_IMPORT_OPTS}"
+		zfs_set_ifs "$OLD_IFS"
 		ZFS_STDERR="$($ZFS_CMD "$pool" 2>&1)"
+		zfs_set_ifs "$TMP_IFS"
 		ZFS_ERROR="$?"
 		if [ "${ZFS_ERROR}" != 0 ]
 		then
 			[ "$quiet" != "y" ] && zfs_log_failure_msg "${ZFS_ERROR}"
 
 			disable_plymouth
-			echo ""
-			echo "Command: ${ZFS_CMD} '$pool'"
-			echo "Message: $ZFS_STDERR"
-			echo "Error: $ZFS_ERROR"
-			echo ""
-			echo "Failed to import pool '$pool'."
-			echo "Manually import the pool and exit."
-			/bin/sh
+			if [ "$?" != 999 ]; then
+				echo ""
+				echo "Command: ${ZFS_CMD} '$pool'"
+				echo "Message: $ZFS_STDERR"
+				echo "Error: $ZFS_ERROR"
+				echo ""
+				echo "Failed to import pool '$pool'."
+				echo "Manually import the pool and exit."
+				emergency_shell
+			else
+				[ -n "$ORIG_IFS" ] && IFS=$ORIG_IFS
+				return 1
+			fi
 		fi
 	fi
 
@@ -700,21 +727,27 @@ mount_fs()
 	[ -n "${ZFS_DEBUG}" ] && \
 	    zfs_log_begin_msg "CMD: '$ZFS_CMD ${fs} ${rootmnt}/${mountpoint}'"
 
+	zfs_set_ifs "$OLD_IFS"
 	ZFS_STDERR=$(${ZFS_CMD} "${fs}" "${rootmnt}/${mountpoint}" 2>&1)
+	zfs_set_ifs "$TMP_IFS"
 	ZFS_ERROR=$?
 	if [ "${ZFS_ERROR}" != 0 ]
 	then
 		[ "$quiet" != "y" ] && zfs_log_failure_msg "${ZFS_ERROR}"
 
 		disable_plymouth
-		echo ""
-		echo "Command: ${ZFS_CMD} ${fs} ${rootmnt}/${mountpoint}"
-		echo "Message: $ZFS_STDERR"
-		echo "Error: $ZFS_ERROR"
-		echo ""
-		echo "Failed to mount ${fs} on ${rootmnt}/${mountpoint}."
-		echo "Manually mount the filesystem and exit."
-		/bin/sh
+		if [ "$?" != 999 ]; then
+			echo ""
+			echo "Command: ${ZFS_CMD} ${fs} ${rootmnt}/${mountpoint}"
+			echo "Message: $ZFS_STDERR"
+			echo "Error: $ZFS_ERROR"
+			echo ""
+			echo "Failed to mount ${fs} on ${rootmnt}/${mountpoint}."
+			echo "Manually mount the filesystem and exit."
+			emergency_shell
+		else
+			return 1
+		fi
 	else
 		[ "$quiet" != "y" ] && zfs_log_end_msg
 	fi
@@ -752,24 +785,28 @@ decrypt_fs()
 			[ "$quiet" != "y" ] && zfs_log_failure_msg "${ZFS_ERROR}"
 
 			disable_plymouth
-			echo ""
-			echo "Command: $ZFS_CMD"
-			echo "Message: $ZFS_STDERR"
-			echo "Error: $ZFS_ERROR"
-			echo ""
-			echo "Failed to load $mod module."
-			echo "Please verify that it is availible on the initrd image"
-			echo "(without it it won't be possible to unlock the filesystem)"
-			echo "and rerun:  $ZFS_CMD"
-			/bin/sh
-		else
-			[ "$quiet" != "y" ] && zfs_log_end_msg
+			if [ "$?" != 999 ]; then
+				echo ""
+				echo "Command: $ZFS_CMD"
+				echo "Message: $ZFS_STDERR"
+				echo "Error: $ZFS_ERROR"
+				echo ""
+				echo "Failed to load $mod module."
+				echo "Please verify that it is availible on the initrd image"
+				echo "(without it it won't be possible to unlock the filesystem)"
+				echo "and rerun:  $ZFS_CMD"
+				emergency_shell
+			else
+				return 1
+			fi
 		fi
 	done
 
 	# If the key isn't availible, then this will fail!
 	ZFS_CMD="${ZFS} key -l -r $fs"
+	zfs_set_ifs "$OLD_IFS"
 	ZFS_STDERR="$(${ZFS_CMD} 2>&1)"
+	zfs_set_ifs "$TMP_IFS"
 	ZFS_ERROR="$?"
 
 	if [ "${ZFS_ERROR}" != 0 ]
@@ -777,15 +814,19 @@ decrypt_fs()
 		[ "$quiet" != "y" ] && zfs_log_failure_msg "${ZFS_ERROR}"
 
 		disable_plymouth
-		echo ""
-		echo "Command: $ZFS_CMD"
-		echo "Message: $ZFS_STDERR"
-		echo "Error: $ZFS_ERROR"
-		echo ""
-		echo "Failed to load zfs encryption wrapper key (s)."
-		echo "Please verify dataset property 'keysource' for datasets"
-		echo "and rerun:  $ZFS_CMD"
-		/bin/sh
+		if [ "$?" != 999 ]; then
+			echo ""
+			echo "Command: $ZFS_CMD"
+			echo "Message: $ZFS_STDERR"
+			echo "Error: $ZFS_ERROR"
+			echo ""
+			echo "Failed to load zfs encryption wrapper key (s)."
+			echo "Please verify dataset property 'keysource' for datasets"
+			echo "and rerun:  $ZFS_CMD"
+			emergency_shell
+		else
+			return 1
+		fi
 	else
 		[ "$quiet" != "y" ] && zfs_log_end_msg
 	fi
@@ -803,22 +844,28 @@ destroy_fs()
 	    zfs_log_begin_msg "Destroying '$fs'"
 
 	ZFS_CMD="${ZFS} destroy $fs"
+	zfs_set_ifs "$OLD_IFS"
 	ZFS_STDERR="$(${ZFS_CMD} 2>&1)"
+	zfs_set_ifs "$TMP_IFS"
 	ZFS_ERROR="$?"
 	if [ "${ZFS_ERROR}" != 0 ]
 	then
 		[ "$quiet" != "y" ] && zfs_log_failure_msg "${ZFS_ERROR}"
 
 		disable_plymouth
-		echo ""
-		echo "Command: $ZFS_CMD"
-		echo "Message: $ZFS_STDERR"
-		echo "Error: $ZFS_ERROR"
-		echo ""
-		echo "Failed to destroy '$fs'. Please make sure that '$fs' is not availible."
-		echo "Hint: Try:  zfs destroy -Rfn $fs"
-		echo "If this dryrun looks good, then remove the 'n' from '-Rfn' and try again."
-		/bin/sh
+		if [ "$?" != 999 ]; then
+			echo ""
+			echo "Command: $ZFS_CMD"
+			echo "Message: $ZFS_STDERR"
+			echo "Error: $ZFS_ERROR"
+			echo ""
+			echo "Failed to destroy '$fs'. Please make sure that '$fs' is not availible."
+			echo "Hint: Try:  zfs destroy -Rfn $fs"
+			echo "If this dryrun looks good, then remove the 'n' from '-Rfn' and try again."
+			emergency_shell
+		else
+			return 1
+		fi
 	else
 		[ "$quiet" != "y" ] && zfs_log_end_msg
 	fi
@@ -847,22 +894,28 @@ clone_snap()
 	ZFS_CMD="${ZFS} clone -o canmount=noauto -o mountpoint=none"
 	ZFS_CMD="${ZFS_CMD} -o org.zol:mountpoint=${mountpoint}"
 	ZFS_CMD="${ZFS_CMD} $snap $destfs"
+	zfs_set_ifs "$OLD_IFS"
 	ZFS_STDERR="$(${ZFS_CMD} 2>&1)"
+	zfs_set_ifs "$TMP_IFS"
 	ZFS_ERROR="$?"
 	if [ "${ZFS_ERROR}" != 0 ]
 	then
 		[ "$quiet" != "y" ] && zfs_log_failure_msg "${ZFS_ERROR}"
 
 		disable_plymouth
-		echo ""
-		echo "Command: $ZFS_CMD"
-		echo "Message: $ZFS_STDERR"
-		echo "Error: $ZFS_ERROR"
-		echo ""
-		echo "Failed to clone snapshot."
-		echo "Make sure that the any problems are corrected and then make sure"
-		echo "that the dataset '$destfs' exists and is bootable."
-		/bin/sh
+		if [ "$?" != 999 ]; then
+			echo ""
+			echo "Command: $ZFS_CMD"
+			echo "Message: $ZFS_STDERR"
+			echo "Error: $ZFS_ERROR"
+			echo ""
+			echo "Failed to clone snapshot."
+			echo "Make sure that the any problems are corrected and then make sure"
+			echo "that the dataset '$fs' exists and is bootable."
+			emergency_shell
+		else
+			return 1
+		fi
 	else
 		[ "$quiet" != "y" ] && zfs_log_end_msg
 	fi
@@ -879,20 +932,26 @@ rollback_snap()
 	[ "$quiet" != "y" ] && zfs_log_begin_msg "Rollback $snap"
 
 	ZFS_CMD="${ZFS} rollback -Rf $snap"
+	zfs_set_ifs "$OLD_IFS"
 	ZFS_STDERR="$(${ZFS_CMD} 2>&1)"
+	zfs_set_ifs "$TMP_IFS"
 	ZFS_ERROR="$?"
 	if [ "${ZFS_ERROR}" != 0 ]
 	then
 		[ "$quiet" != "y" ] && zfs_log_failure_msg "${ZFS_ERROR}"
 
 		disable_plymouth
-		echo ""
-		echo "Command: $ZFS_CMD"
-		echo "Message: $ZFS_STDERR"
-		echo "Error: $ZFS_ERROR"
-		echo ""
-		echo "Failed to rollback snapshot."
-		/bin/sh
+		if [ "$?" != 999 ]; then
+			echo ""
+			echo "Command: $ZFS_CMD"
+			echo "Message: $ZFS_STDERR"
+			echo "Error: $ZFS_ERROR"
+			echo ""
+			echo "Failed to rollback snapshot."
+			emergency_shell
+		else
+			return 1
+		fi
 	else
 		[ "$quiet" != "y" ] && zfs_log_end_msg
 	fi
@@ -1051,6 +1110,26 @@ disable_plymouth()
 	then
 		/bin/plymouth hide-splash >/dev/null 2>&1
 	else
+		# No plymouth. Return a high number that shouldn't
+		# mean anything to anyone but us.
 		return 999
 	fi
 }
+
+# This is defined in dracut, but nowhere
+# else. So create a wrapper.
+if ! type emergency_shell > /dev/null 2>&1 ; then
+	emergency_shell() { /bin/sh -i -l; }
+fi
+
+# For some reason, some functions in the library have a problem
+# with a changed IFS, so this function goes around that.
+zfs_set_ifs() {
+	local tIFS="$1"
+	if [ -n "$tIFS" ]
+	then
+		TMP_IFS="$IFS"
+		IFS="$tIFS"
+	fi
+}
+
