Move udev initrd hooks into zfsutils to mount zdev-based pools at boot
@TODO: Add commit message.

Closes: dajhorn/pkg-zfs#39
Closes: zfsonlinux/zfs#811

diff --git a/debian/tree/zfsutils/usr/share/initramfs-tools/hooks/zdev b/debian/tree/zfsutils/usr/share/initramfs-tools/hooks/zdev
--- a/debian/tree/zfsutils/usr/share/initramfs-tools/hooks/zdev
+++ b/debian/tree/zfsutils/usr/share/initramfs-tools/hooks/zdev
@@ -5,25 +5,17 @@
 
 
 # This module depends on these initramfs-tools modules.
-PREREQ="zdev"
+PREREQ="udev"
+ 
+# ZFS on Linux uses udev for device node creation.
+PREREQ_UDEV_RULES="60-zpool.rules 60-zvol.rules"
 
 # These prerequisites are provided by the zfs package. The zdb utility is not
 # strictly required, but it can be useful at the initramfs recovery prompt.
 COPY_EXEC_LIST=" \
-  /sbin/zdb \
-  /sbin/zpool \
-  /sbin/zfs \
-  /sbin/mount.zfs \
+  /lib/udev/zvol_id \
+  /lib/udev/zpool_id \
   "
-
-# These prerequisites are provides by other packages.
-COPY_EXEC_LIST="$COPY_EXEC_LIST \
-  /bin/hostname \
-  /sbin/blkid \
-  "
-
-# Explicitly specify all modules because dependency resolution is unreliable here.
-MANUAL_ADD_MODULES_LIST="zlib_deflate spl zavl zcommon znvpair zunicode zfs"
 
 # Generic result code.
 RC=0
@@ -52,6 +44,7 @@ fi
 . /usr/share/initramfs-tools/hook-functions
 
 mkdir -p "$DESTDIR/etc/"
+mkdir -p "$DESTDIR/lib/udev/rules.d/"
 
 # ZDB uses pthreads for some functions, but the library dependency is not
 # automatically detected. The `find` utility and extended `cp` options are
@@ -59,23 +52,28 @@ mkdir -p "$DESTDIR/etc/"
 # multi-arch installations.
 cp --target-directory="$DESTDIR" --parents $(find /lib -type f -name libgcc_s.so.1)
 
+
+for ii in $PREREQ_UDEV_RULES
+do
+	if [ -e "/etc/udev/rules.d/$ii" ]
+	then
+		cp -p "/etc/udev/rules.d/$ii" "$DESTDIR/lib/udev/rules.d/"
+	elif [ -e "/lib/udev/rules.d/$ii" ]
+	then
+		cp -p "/lib/udev/rules.d/$ii" "$DESTDIR/lib/udev/rules.d/"
+	else
+		echo "Error: Missing udev rule: $ii"
+		echo "       This file must be in the /etc/udev/rules.d or /lib/udev/rules.d directory."
+		exit 1
+	fi
+done
+
 for ii in $COPY_EXEC_LIST
 do
 	copy_exec "$ii"
 done
 
-for ii in $MANUAL_ADD_MODULES_LIST
-do
-	manual_add_modules "$ii"
-done
-
-if [ -f "/etc/hostname" ]
+if [ -e "/etc/zfs/" ]
 then
-	cp -p "/etc/hostname" "$DESTDIR/etc/"
-else
-	hostname >"$DESTDIR/etc/hostname"
+	cp -a "/etc/zfs/" "$DESTDIR/etc/"
 fi
-
-# The spl package ensures that the /etc/hostid file exists.
-# NB: Commentary in the spl.postinst script.
-cp -p "/etc/hostid" "$DESTDIR/etc/hostid"
